name: Build and Release C++

on:
  push:
    tags:
    - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile main.cpp (Static Build)
      run: g++ main.cpp -O2 -static -static-libgcc -static-libstdc++ -o main.exe

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: main.exe
