name: Build and Release C++

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add MinGW to PATH
        run: echo "C:\msys64\mingw64\bin" >> $env:GITHUB_PATH

      - name: Compile (Static Build)
        run: g++ main.cpp -O2 -static -static-libgcc -static-libstdc++ -o TheForgottenPath.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: TheForgottenPath.exe
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: TheForgottenPath.exe
